name_or_path: post_training/resource/results/checkpoint-17500/
tokenizer_name_or_path: null
archive: null
block_name: LlamaDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: null
reference_dtype: bfloat16
